-- print(bold().."\n\n")
-- print(white()     ..[[      /\      ]])
-- print(cyanBright()..[[     /  \     ]])
-- print(cyan()      ..[[    /\   \    ]])
-- print(blueBright()..[[   /      \   ]])
-- print(blue()      ..[[  /   ,,   \  ]])
-- print(              [[ /   |  |  -\ ]])
-- print(              [[/_-''    ''-_\]])
-- print(reset())

print(bold() .. "\n")
print(red() .. [[    .---.    ]])
print(red() .. [[   /     \   ]])
print(red() .. [[   \.@-@./   ]])
print(red() .. [[   /`\_/`\   ]])
print(red() .. [[  //  _  \\  ]])
print(red() .. [[ | \     )|_ ]])
print([[/`\_`>  <_/ \]])
print([[\__/'---'\__/]])
print(reset())
